-- 7월 기준 더한 값 상위 3개 큰 순서대로 조회
SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
      FROM JULY J
      GROUP BY FLAVOR) NT ON NT.FLAVOR = F.FLAVOR
ORDER BY (NT.TOTAL_ORDER + F.TOTAL_ORDER) DESC
LIMIT 3