SELECT APNT_NO, PT_NAME, APPOINTMENT.PT_NO, APPOINTMENT.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT
JOIN PATIENT ON APPOINTMENT.PT_NO = PATIENT.PT_NO
JOIN DOCTOR ON APPOINTMENT.MDDR_ID = DOCTOR.DR_ID
WHERE APPOINTMENT.MCDP_CD = 'CS' 
    AND APNT_CNCL_YN = 'N'
    AND APNT_YMD BETWEEN TO_DATE('2022-04-13 00:00:00','YYYY-MM-DD HH24:MI:SS')
                     AND TO_DATE('2022-04-13 23:59:59','YYYY-MM-DD HH24:MI:SS')
ORDER BY APNT_YMD